version: '3.8'

services:
  admira-etl:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ADS_API_URL=${ADS_API_URL}
      - CRM_API_URL=${CRM_API_URL}
      - SINK_URL=${SINK_URL}
      - SINK_SECRET=${SINK_SECRET}
      - PORT=8080
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

